name: "react-ds-core-form/chromatic"
on:
  pull_request:
    paths: [packages/react/ds-core-form/**]
jobs:
  test-compile:
    uses: ./.github/workflows/chromatic._template.yml
    secrets:
      CHROMATIC_PROJECT_TOKEN: ${{ secrets.CHROMATIC_TOKEN_CANONICAL_REACT_DS_CORE_FORM }}
    with:
      working-directory: packages/react/ds-core-form
